import java.time.LocalDate

plugins {
    kotlin("multiplatform")
    id("com.android.library")
    id("org.jetbrains.compose")
    id("org.jetbrains.kotlin.plugin.compose")
}

// The drawer's version line used to carry a date somebody had to remember to bump, so it
// always read older than the build you were looking at. Generate it instead. Rewritten only
// when the value actually changes, so same-day rebuilds stay incremental.
val generateBuildStamp by tasks.registering {
    val outDir = layout.buildDirectory.dir("generated/appversion")
    outputs.dir(outDir)
    doLast {
        val date = LocalDate.now().toString()
        val file = outDir.get().file("app/smugly/BuildStamp.kt").asFile
        val text = buildString {
            appendLine("package app.smugly")
            appendLine()
            appendLine("/** Generated by :shared:generateBuildStamp at build time - do not edit. */")
            appendLine("internal const val BUILD_STAMP_DATE: String = \"" + date + "\"")
        }
        if (!file.exists() || file.readText() != text) {
            file.parentFile.mkdirs()
            file.writeText(text)
        }
    }
}

kotlin {
    compilerOptions {
        freeCompilerArgs.add("-Xexpect-actual-classes")
    }

    androidTarget {
        compilations.all {
            compileTaskProvider.configure {
                compilerOptions {
                    jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17)
                }
            }
        }
    }

    jvm("desktop") {
        compilations.all {
            compileTaskProvider.configure {
                compilerOptions {
                    jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17)
                }
            }
        }
    }

    listOf(
        iosX64(),
        iosArm64(),
        iosSimulatorArm64()
    ).forEach { target ->
        target.binaries.framework {
            baseName = "SmuglyShared"
            isStatic = true
        }
    }

    sourceSets {
        val commonMain by getting {
            // Task provider, not a plain path: that is what carries the build dependency.
            kotlin.srcDir(generateBuildStamp)
            dependencies {
                implementation(compose.runtime)
                implementation(compose.foundation)
                implementation(compose.animation)
                implementation(compose.material3)
                implementation(compose.ui)
                implementation(compose.materialIconsExtended)
                implementation(compose.components.resources)
            }
        }
        val commonTest by getting {
            dependencies {
                implementation(kotlin("test"))
            }
        }

        val jvmAndAndroidMain by creating {
            dependsOn(commonMain)
            dependencies {
                api("org.json:json:20240303")
            }
        }
        val jvmAndAndroidTest by creating {
            dependsOn(commonTest)
            dependencies {
                implementation(kotlin("test"))
            }
        }

        val androidMain by getting {
            dependsOn(jvmAndAndroidMain)
            dependencies {
                implementation("androidx.activity:activity-compose:1.10.1")
                implementation("androidx.compose.ui:ui-tooling-preview:1.7.8")
            }
        }
        val androidUnitTest by getting {
            dependsOn(jvmAndAndroidTest)
        }

        val desktopMain by getting {
            dependsOn(jvmAndAndroidMain)
            dependencies {
                implementation(compose.desktop.currentOs)
            }
        }
        val desktopTest by getting {
            dependsOn(jvmAndAndroidTest)
        }

        val iosX64Main by getting
        val iosArm64Main by getting
        val iosSimulatorArm64Main by getting
        val iosMain by creating {
            dependsOn(commonMain)
            iosX64Main.dependsOn(this)
            iosArm64Main.dependsOn(this)
            iosSimulatorArm64Main.dependsOn(this)
        }
    }
}

android {
    namespace = "app.smugly.shared"
    compileSdk = 36
    defaultConfig {
        minSdk = 24
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    buildFeatures {
        compose = true
    }
}

compose.resources {
    publicResClass = true
    packageOfResClass = "app.smugly.shared.generated.resources"
    generateResClass = always
}
